# lxc, Linux Containers

lxc.net.0.type = veth
# Optionally edit the network bridge name for "lxc.net.0.link".
#
# One reason why this may be needed is when we have ubuntu's Snap installed.
# Snap forces the default lxcbr0 network bridge to be unmanaged.
# Therefore create our managed bridge by:
#
# $ lxc network create lxcbr1
#
# lxc seems to recommend using the ufw firewall, so run:
#
# $ ufw enable
# $ ufw allow in on lxcbr1
# $ ufw route allow in on lxcbr1
# $ ufw route allow out on lxcbr1
#
# For user (non-root) containers, edit lxc-usernet:
#
# $ echo "$(id -un) veth lxcbr1 10" | sudo tee -a /etc/lxc/lxc-usernet
lxc.net.0.link = lxcbr0

lxc.idmap = u 0 100000 65536
lxc.idmap = g 0 100000 65536

# Create, start, and attach to a container with
#
# lxc-create -n $CNAME --template download -- --dist ubuntu --release questing --arch amd64
# lxc-unpriv-start -n $CNAME
# lxc-unpriv-attach -n $CNAME
#
# The rootfs for user (non-root) containers is:
# lxc.lxcpath = $HOME/.local/share/lxc/<container-name>/rootfs
